force-app/main/default/objects/DOM_CaseExtension__c/DOM_CaseExtension__c.object-meta.xml
<CustomObject>
    <label>Case Extension</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Case Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases Extension</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DOM_CaseExtension__c/fields/DOM_caseId__c.field-meta.xml
<CustomField>
    <fullName>DOM_caseId__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Cases Extension</relationshipLabel>
    <relationshipName>Cases_Extension2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DOM_CaseExtension__c/fields/DOM_Status__c.field-meta.xml
<CustomField>
    <fullName>DOM_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
            <value>
                <fullName>Lang</fullName>
            </value>
            <value>
                <fullName>DRV</fullName>
            </value>
            <value>
                <fullName>ENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APP_CaseExtensionService.cls
public with sharing class APP_CaseExtensionService {
    public static void sendMailWithAImetrics(List<DOM_CaseExtension__c> caseExtensions) {

        if (caseExtensions == null || caseExtensions.isEmpty()) {
            throw new IllegalArgumentException('Case extensions cannot be null or empty');
        }

        // TODO: Evaluate if we need to handle multiple case extensions
        if (caseExtensions.size() > 1) {
            System.debug(LoggingLevel.WARN, 'Expected exactly one case extension, but found: ' + caseExtensions.size());
            return;
        }

        try {
            if ( caseExtensions.get(0).DOM_Status__c == DOM_Config.LAUNCH_RESULT_EXTENSION_STATUS ) {
                // TODO: Evaluate if this query can be cached
                Case associatedCase = [SELECT Id, CaseNumber FROM Case WHERE Id = :caseExtensions[0].DOM_caseId__c LIMIT 1];
                EVAL_EmailService.sendAIMetrics(associatedCase);
            }
        } catch (EVAL_EmailService.EVAL_EmailServiceException e) {
            System.debug(LoggingLevel.ERROR, 'Error sending email with AI metrics: ' + e.getMessage());
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, 'Unexpected error sending email with AI metrics: ' + e.getMessage());
        }
    }
}